export const skills = [
    { title: "Scrum", experience: 40 },
    { title: "Shape Up", experience: 10 },
    { title: "Java", experience: 30 },
    { title: "Javascript", experience: 70 },
    { title: "GCP", experience: 20 },
    { title: "Firebase", experience: 40 },
    { title: "PHP", experience: 10 },
    { title: "Swift", experience: 10 },
    { title: "Nodejs", experience: 60 },
    { title: "MongoDb", experience: 50 },
    { title: "Oracle", experience: 40 },
    { title: "Angular", experience: 80 },
    { title: "Reactjs", experience: 60 },
    { title: "Vuejs", experience: 20 },
    { title: "SwiftUI", experience: 5 },
    { title: "Testing", experience: 20 },
    { title: "Git", experience: 50 },
    { title: "GitFlow", experience: 50 },
    { title: "Docker", experience: 50 },
    { title: "Docker Compose", experience: 50 },
  ];